### ISSUE TITLE
Missing PostGIS function shields_get_single_filename

### ISSUE THREAD

**Issue by bnordgren** [bnordgren/TopOSM#1]
@asciiphil The repository is missing the definition of `shields_get_single_filename`. Would it be possible to get it added? Or perhaps a description of what it's supposed to do? 

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "./toposm.py", line 392, in run
    mapnik.load_map(map, self.mapname + ".xml")
RuntimeError: Postgis Plugin: ERROR:  function shields_get_single_filename(text, text, unknown, integer) does not exist
LINE 1: SELECT * FROM (SELECT way, shields_get_single_filename(netwo...
                                   ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
in executeQuery Full sql was: 'SELECT * FROM (SELECT way, shields_get_single_filename(network, ref, 'cutouts', 20) AS route_shield
               FROM osm_line
	       WHERE osm_id < 0
                 AND route = 'road'
                 AND (network = 'US:I' AND char_length(ref) BETWEEN 1 AND 2)
               ORDER BY ST_Length(way) DESC
	    ) AS shields LIMIT 0'
  encountered during parsing of layer 'shields-very-low-zoom' in Layer at line 837 of 'features.xml'
```

**Comment by bnordgren** [comment]
Looking further down the `features.xml` file, it looks like we're also missing: 

* `shields_get_filename`
* `shields_get_route_membership`

**Comment by bnordgren** [comment]
If I'm interpreting the style files correctly, the ShieldSymbolizers do not write the route number over the graphic if the `route_shield` contains something. This leads me to suspect that custom shields were rendered for various routes, the filenames for which were stored in the PostGIS database.

**Comment by bnordgren** [comment]
It seems Ahlzen's version may be more targeted at the OSM postgis database without requiring the missing black box (pre-rendered shields). It just overlays the `roadnumber` on top of the shield background (which are present). Will have to try reverting at least the roads layers of `features.xml.templ` and `shields.inc`

**Comment by bnordgren** [comment]
Reverted to @Ahlzen's styling with  530195b
